inherit_from:
  - https://raw.githubusercontent.com/hanami/hanami/master/.rubocop.yml

Metrics/BlockLength:
  Exclude:
  # Ignore RSpec DSL
  - spec/**/*

# Avoid parameter lists longer than four parameters.
ParameterLists:
  Max: 4
  CountKeywordArgs: true

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Do not favor modifier if/unless usage when you have a single-line body
IfUnlessModifier:
  Enabled: false

# Allow case equality operator (in limited use within the specs)
CaseEquality:
  Enabled: false

# Constants do not always have to use SCREAMING_SNAKE_CASE
ConstantName:
  Enabled: false

# Not all trivial readers/writers can be defined with attr_* methods
TrivialAccessors:
  Enabled: false

# Allow empty lines around class body
EmptyLinesAroundClassBody:
  Enabled: false

# Allow empty lines around module body
EmptyLinesAroundModuleBody:
  Enabled: false

# Allow empty lines around block body
EmptyLinesAroundBlockBody:
  Enabled: false

# Allow multiple line operations to not require indentation
MultilineOperationIndentation:
  Enabled: false

# Prefer String#% over Kernel#sprintf
FormatString:
  Enabled: false

# Align if/else blocks with the variable assignment
EndAlignment:
  EnforcedStyleAlignWith: variable

# Do not always align parameters when it is easier to read
AlignParameters:
  Exclude:
    - spec/**/*_spec.rb

# Prefer #kind_of? over #is_a?
ClassCheck:
  EnforcedStyle: kind_of?

# Do not prefer double quotes to be used when %q or %Q is more appropriate
UnneededPercentQ:
  Enabled: false

# Do not prefer lambda.call(...) over lambda.(...)
LambdaCall:
  Enabled: false

# Allow additional spaces
ExtraSpacing:
  Enabled: false

# All objects can still be mutated if their eigenclass is patched
RedundantFreeze:
  Enabled: false

# Prefer using `fail` when raising and `raise` when reraising
SignalException:
  Enabled: false
Style/FileName:
  Exclude:
    - lib/hanami-mailer.rb
